baseURL = "https://bedatalab.github.io/"
languageCode = "en-us"
title = "BE Data Lab"
theme = "hugo-theme-nix"

[params]
  Name = "MIT BE Data Lab"
  HeaderUsername = "bedl"
  HeaderHostname = "MIT-BE"
  About = "Here we summarize who we are and what we do. A few sentences should suffice. Nothing too fancy. Just a few words. Maybe a bit more. I think that's enough."
  ProfilePicture = "/img/BEDL_Logo_notxt.png"
  GithubID = "bedatalab"

[menu]
  [[menu.header]]
    name = "About"
    weight = 1
    url = "/about"
  [[menu.header]]
    name = "Resources"
    weight = 3
    url = "/resources"
  [[menu.header]]
    name = "Q&A"
    weight = 4
    url = "/qanda"
  [[menu.header]]
    name = "Fellows+Staff"
    weight = 2
    url = "/people"
  [[menu.header]]
    name = "Make_appointment"
    weight = 0
    url = "/appointments"
