baseURL = "https://bedatalab.github.io/"
languageCode = "en-us"
title = "BE Data Lab"
theme = "hugo-theme-nix"

[params]
  Name = "MIT BE Data Lab"
  HeaderUsername = "bedl"
  HeaderHostname = "MIT-BE"
  About = "We provide peer coaching on data analysis and coding for life sciences researchers and students at MIT."
  ProfilePicture = "/img/BEDL_Logo.png"
  GithubID = "bedatalab"

[menu]
  [[menu.header]]
    name = "About"
    weight = 1
    url = "/about"
  [[menu.header]]
    name = "Resources"
    weight = 4
    url = "/resources"
  [[menu.header]]
    name = "Q&A"
    weight = 2
    url = "/qanda"
  [[menu.header]]
    name = "Fellows+Staff"
    weight = 3
    url = "/people"
  [[menu.header]]
    name = "Make_appointment"
    weight = 0
    url = "/appointments"
