backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/img/uploads" # Media files will be stored in the repo under images/uploads
collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
        slug: "{{name}}"
      - file: "content/qanda.md"
        label: "Q & A Page"
        name: "qanda"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
        slug: "{{name}}"
      - file: "content/resources.md"
        label: "Resources Page"
        name: "resources"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
        slug: "{{name}}"
      - file: "content/appointments.md"
        label: "Appointments Page"
        name: "appointments"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
        slug: "{{name}}"
      - file: "content/people.md"
        label: "People Page"
        name: "people"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
        slug: "{{name}}"
